### ISSUE TITLE
Make the cluster description part of the configuration

### ISSUE THREAD

**Issue by jkremser** [jvm-operators/ansible-openshift-spark-operator#1]
it would be nice to have a way to put also CM or CR directly in the yaml params of the role. Something like:

```yaml
- hosts: localhost
  roles:
    - role: jiri_kremser.spark_operator
      cluster:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: my-spark-cluster
          labels:
            radanalytics.io/kind: sparkcluster
        data:
          config: |-
            worker:
              instances: "2"
```
